development:
  adapter: postgresql
  encoding: utf8
  database: suite_success_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: suite_success_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: suite_success_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST